---
require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "vendor/**/*"
    - "node_modules/**/*"
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true

Rails:
  Enabled: true

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
